// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApp.Data;

namespace WebApp.Data.Migrations.ApplicationDbContextMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180524113952_AddTradePointsSchema")]
    partial class AddTradePointsSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp.Models.DataFiles.DataFile", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Content")
                        .IsRequired();

                    b.Property<byte[]>("Hash");

                    b.Property<bool>("IsProcessed");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasFilter("[Hash] IS NOT NULL");

                    b.ToTable("DataFiles");
                });

            modelBuilder.Entity("WebApp.Models.TradePoints.ATM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DataFileId");

                    b.HasKey("Id");

                    b.HasIndex("DataFileId");

                    b.ToTable("ATMs");
                });

            modelBuilder.Entity("WebApp.Models.TradePoints.InfoKiosk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DataFileId");

                    b.HasKey("Id");

                    b.HasIndex("DataFileId");

                    b.ToTable("InfoKiosks");
                });

            modelBuilder.Entity("WebApp.Models.TradePoints.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DataFileId");

                    b.HasKey("Id");

                    b.HasIndex("DataFileId");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("WebApp.Models.TradePoints.ATM", b =>
                {
                    b.HasOne("WebApp.Models.DataFiles.DataFile", "DataFile")
                        .WithMany()
                        .HasForeignKey("DataFileId");
                });

            modelBuilder.Entity("WebApp.Models.TradePoints.InfoKiosk", b =>
                {
                    b.HasOne("WebApp.Models.DataFiles.DataFile", "DataFile")
                        .WithMany()
                        .HasForeignKey("DataFileId");
                });

            modelBuilder.Entity("WebApp.Models.TradePoints.Office", b =>
                {
                    b.HasOne("WebApp.Models.DataFiles.DataFile", "DataFile")
                        .WithMany()
                        .HasForeignKey("DataFileId");
                });
#pragma warning restore 612, 618
        }
    }
}
